#!/usr/bin/python3

import docker_mounter
import cvmfs_publisher
import argparse

helpString = "Download a Docker image and publish it to CVMFS"
parser = argparse.ArgumentParser(description=helpString,
        formatter_class=argparse.RawTextHelpFormatter)
parser.add_argument("image", type=str,
        help="Docker image and tag, e.g. centos:6")
parser.add_argument("-r","--registry", required=False, type=str,
        help="Registry URI")
private_registry_args = parser.add_argument_group("Registry Credentials")
private_registry_args.add_argument("-u","--username", required=False, type=str,
        help="Username for registry")
private_registry_args.add_argument("-t","--token", required=False, type=str,
        help="Authentication token for registry")
args = parser.parse_args()

creds = (args.username,args.token)
if creds.count(None) == 1:
    parser.error("Must provide both authentication username and token or neither!")

docker_image = docker_mounter.get_image(image=args.image, username=args.username, token=args.token, registry=args.registry)
mount_info = docker_mounter.overlay_mount(docker_image)

## PUBLISH IN CVMFS HERE

docker_mounter.overlay_cleanup(mount_info.mount_point, mount_info.dir_to_cleanup)
